version: '3.8'

services:
  app:
    build: .
    container_name: transaction-pretest
    ports:
      - "3602:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: node app.js
    restart: unless-stopped